name: "Setup Secret"

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test Action
    runs-on: ubuntu-latest
    needs: dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: See version
        uses: ./
        with:
          name:  LAST_RUNNER_ID
          value: ${{ github.run_id }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: post-test
          client-payload: '{"ref": "${{ github.run_id }}"}'