name: "Setup Secret"

on:
  pull_request:
    branches:
      - master

jobs:
  pretest:
    name: Set Secret test
    runs-on: ubuntu-latest
    needs: dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: See version
        uses: ./
        with:
          name:  LAST_RUNNER_ID
          value: ${{ github.run_id }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

  posttest:
    name: Validate created test
    runs-on: ubuntu-latest
    needs: pretest

    steps:
      - name: Validate Stored Secret
        if: ${{ secrets.LAST_RUNNER_ID }} != ${{ github.event.client_payload.ref }}
        run: exit 1